name: Connect to macOS VNC
on: [push, workflow_dispatch]

jobs:
  vnc-connect:
    runs-on: macos-15
    steps:
      - name: Set Runner Password
        run: |
          # تغيير باسورد مستخدم الـ runner ليكون 123456
          sudo dscl . -passwd /Users/runner 123456 || echo "123456" | sudo passwd runner

      - name: Enable macOS Screen Sharing (VNC)
        run: |
          # تفعيل مشاركة الشاشة بأمر نظيف متوافق مع macOS 15 وبدون الخيارات الملغية
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -privs -all -restart -agent

      - name: Download and Configure Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          curl -L -o ngrok.zip https://bin.equinox.io/c/b34t2HbgKoD/ngrok-v3-stable-darwin-arm64.zip
          unzip ngrok.zip
          chmod +x ./ngrok
          ./ngrok config add-authtoken $NGROK_AUTH_TOKEN

      - name: Start Ngrok Tunnel
        run: |
          ./ngrok tcp 5900 --log=stdout &
          sleep 10
          
          echo "=========================================================="
          echo "Connect to this address using your VNC Viewer:"
          curl --silent http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[^"]*'
          echo "=========================================================="
          
          # إبقاء السيرفر شغال لمدة ساعة كاملة لتتحكم فيه براحتك
          sleep 3600
